# Generated by Django 2.0.3 on 2018-04-02 13:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='domain',
            field=models.CharField(default='example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='salt',
            field=models.CharField(default=core.models.generate_salt, max_length=20),
        ),
    ]
