# Generated by Django 2.0 on 2018-01-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0005_auto_20180125_0939'),
  ]

  operations = [
    migrations.RenameField(
      model_name='token',
      old_name='is_superuse',
      new_name='is_superuser',
    ),
  ]
