# Generated by Django 2.0 on 2018-01-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180125_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_permissions',
            new_name='permissions',
        ),
    ]
