# Generated by Django 2.0 on 2018-01-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180126_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='steamid',
        ),
        migrations.AddField(
            model_name='user',
            name='ingame',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
