# Generated by Django 2.0 on 2018-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180126_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steam',
            field=models.BooleanField(default=True),
        ),
    ]
