# Generated by Django 2.0 on 2018-01-31 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_steam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('immunity', models.DurationField()),
                ('usetime', models.DurationField()),
                ('isadmingroup', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('view_admin_group', 'View server groups'), ('add_admin_group', 'Add server groups'), ('modify_admin_group', 'Edit server groups'), ('delete_admin_group', 'Delete server groups')],
            },
        ),
        migrations.CreateModel(
            name='ServerPermission',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_reservation', models.BooleanField(default=False)),
                ('can_generic', models.BooleanField(default=False)),
                ('can_kick', models.BooleanField(default=False)),
                ('can_ban', models.BooleanField(default=False)),
                ('can_slay', models.BooleanField(default=False)),
                ('can_map', models.BooleanField(default=False)),
                ('can_config', models.BooleanField(default=False)),
                ('can_cvar', models.BooleanField(default=False)),
                ('can_chat', models.BooleanField(default=False)),
                ('can_vote', models.BooleanField(default=False)),
                ('can_password', models.BooleanField(default=False)),
                ('can_rcon', models.BooleanField(default=False)),
                ('can_cheat', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='panelgroup',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='serverrole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServerGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='serverrole',
            unique_together={('user', 'server')},
        ),
        migrations.DeleteModel(
            name='PanelGroup',
        ),
        migrations.DeleteModel(
            name='PanelPermission',
        ),
        migrations.AddField(
            model_name='servergroup',
            name='flags',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ServerPermission'),
        ),
    ]
