# Generated by Django 2.0 on 2018-01-31 12:33

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0012_auto_20180131_1211'),
  ]

  operations = [
    migrations.RenameField(
      model_name='servergroup',
      old_name='isadmingroup',
      new_name='is_admin',
    ),
  ]
