# Generated by Django 2.0 on 2018-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180131_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servergroup',
            name='immunity',
        ),
        migrations.AddField(
            model_name='servergroup',
            name='amunity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
