# Generated by Django 2.0 on 2018-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0015_auto_20180131_1239'),
  ]

  operations = [
    migrations.RenameField(
      model_name='servergroup',
      old_name='amunity',
      new_name='immunity',
    ),
  ]
