# Generated by Django 2.0 on 2018-02-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180201_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='server',
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='user',
        ),
        migrations.AddField(
            model_name='servergroup',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Server'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='core.ServerGroup'),
        ),
        migrations.DeleteModel(
            name='ServerRole',
        ),
    ]
