# Generated by Django 2.0 on 2018-02-05 10:59

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0021_auto_20180202_1159'),
  ]

  operations = [
    migrations.AlterUniqueTogether(
      name='servergroup',
      unique_together={('name', 'server')},
    ),
  ]
