# Generated by Django 2.0 on 2018-02-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180205_1059'),
    ]

    operations = [
    ]
