# Generated by Django 2.0 on 2018-02-11 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0024_auto_20180211_2340'),
  ]

  operations = [
    migrations.AddField(
      model_name='user',
      name='created_at',
      field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
      preserve_default=False,
    ),
    migrations.AddField(
      model_name='user',
      name='updated_at',
      field=models.DateTimeField(auto_now=True),
    ),
    migrations.AlterField(
      model_name='userlogtime',
      name='disconnected',
      field=models.DateTimeField(null=True),
    ),
  ]
