# Generated by Django 2.0.2 on 2018-02-26 09:00

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0029_auto_20180224_2054'),
  ]

  operations = [
    migrations.RenameField(
      model_name='user',
      old_name='ingame',
      new_name='namespace',
    ),
  ]
