# Generated by Django 2.0.2 on 2018-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0030_auto_20180226_0900'),
  ]

  operations = [
    migrations.AddField(
      model_name='token',
      name='due',
      field=models.DateTimeField(null=True),
    ),
  ]
