# Generated by Django 2.0.2 on 2018-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0031_token_due'),
  ]

  operations = [
    migrations.RenameField(
      model_name='servergroup',
      old_name='is_admin',
      new_name='is_supergroup',
    ),
  ]
