# Generated by Django 2.0.2 on 2018-02-27 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0032_auto_20180226_1002'),
  ]

  operations = [
    migrations.AlterField(
      model_name='ban',
      name='length',
      field=models.DurationField(null=True),
    ),
    migrations.AlterField(
      model_name='ban',
      name='server',
      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Server'),
    ),
  ]
