# Generated by Django 2.0.2 on 2018-03-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180301_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ban',
            unique_together={('user', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='mutegag',
            unique_together={('user', 'server')},
        ),
    ]
