# Generated by Django 2.0.2 on 2018-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180301_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutegag',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Server'),
        ),
    ]
