# Generated by Django 2.0.3 on 2018-03-12 06:02

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0039_auto_20180307_2131'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='user',
      name='roles',
    ),
  ]
