# Generated by Django 2.0.3 on 2018-03-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180316_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'permissions': [], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='mutegag',
            options={'permissions': [('view_mutegag', 'Can view a mutegag'), ('add_mutegag_mute', 'Can add a mutegag mute'), ('add_mutegag_gag', 'Can add a mutegag gag')], 'verbose_name': 'mute & gag', 'verbose_name_plural': 'mutes & gags'},
        ),
        migrations.AlterModelOptions(
            name='servergroup',
            options={'permissions': [('view_servergroup', 'Can view server groups')], 'verbose_name': 'server role', 'verbose_name_plural': 'server roles'},
        ),
        migrations.AlterModelOptions(
            name='serverpermission',
            options={'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'permissions': [('view_token', 'Can view tokens')], 'verbose_name': 'token', 'verbose_name_plural': 'tokens'},
        ),
    ]
