# Generated by Django 2.0.3 on 2018-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180320_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ban',
            unique_together=set(),
        ),
    ]
