# Generated by Django 2.0.3 on 2018-04-19 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20180411_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainframe',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned', models.UUIDField(null=True)),
                ('token', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user', 'Can view user'), ('kick_user', 'Can kick user'), ('view_group', 'Can view user group'), ('view_settings', 'Can view settings'), ('view_capabilities', 'Can check capabilities'), ('add_mainframe', 'Can add mainframe'), ('view_mainframe', 'Can check mainframe')]},
        ),
    ]
