# Generated by Django 2.0.3 on 2018-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20180422_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainframe',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
