# Generated by Django 2.0.3 on 2018-05-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_mainframe_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_1',
            field=models.BooleanField(default=False, help_text='O'),
        ),
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_2',
            field=models.BooleanField(default=False, help_text='P'),
        ),
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_3',
            field=models.BooleanField(default=False, help_text='Q'),
        ),
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_4',
            field=models.BooleanField(default=False, help_text='R'),
        ),
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_5',
            field=models.BooleanField(default=False, help_text='S'),
        ),
        migrations.AddField(
            model_name='serverpermission',
            name='can_custom_6',
            field=models.BooleanField(default=False, help_text='T'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_ban',
            field=models.BooleanField(default=False, help_text='DE'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_chat',
            field=models.BooleanField(default=False, help_text='J'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_cheat',
            field=models.BooleanField(default=False, help_text='N'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_config',
            field=models.BooleanField(default=False, help_text='H'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_cvar',
            field=models.BooleanField(default=False, help_text='I'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_generic',
            field=models.BooleanField(default=False, help_text='B'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_kick',
            field=models.BooleanField(default=False, help_text='C'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_map',
            field=models.BooleanField(default=False, help_text='G'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_password',
            field=models.BooleanField(default=False, help_text='L'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_rcon',
            field=models.BooleanField(default=False, help_text='M'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_reservation',
            field=models.BooleanField(default=False, help_text='A'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_slay',
            field=models.BooleanField(default=False, help_text='F'),
        ),
        migrations.AlterField(
            model_name='serverpermission',
            name='can_vote',
            field=models.BooleanField(default=False, help_text='K'),
        ),
    ]
