# Generated by Django 2.0.3 on 2018-05-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20180516_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mutegag',
            unique_together=set(),
        ),
    ]
