# Generated by Django 2.0.5 on 2018-06-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_punishment_is_kicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag'
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
    ]
