# Generated by Django 2.0.6 on 2018-06-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20180615_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerGroup',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('view_role', 'Can view server role')], 'verbose_name': 'server role', 'verbose_name_plural': 'server roles'},
        ),
    ]
