# Generated by Django 2.0.6 on 2018-07-04 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20180621_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user', 'Can view user'), ('kick_user', 'Can kick user'), ('verify_user', 'Can verify user'), ('view_group', 'Can view user group'), ('view_settings', 'Can view settings'), ('view_capabilities', 'Can check capabilities')]},
        ),
        migrations.AlterField(
            model_name='punishment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punishment_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
