# Generated by Django 2.0.6 on 2018-07-13 00:06

from django.db import migrations, models
from django.template.defaultfilters import slugify


def forwards(apps, schema_editor):
    Server = apps.get_model('core', 'Server')
    for row in Server.objects.all():
        row.slug = slugify(row.name)[:50]
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_server_slug'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(),
        ),
    ]
