# Generated by Django 2.1.1 on 2018-09-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20180713_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainframe',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='punishment',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [], 'verbose_name': 'server role', 'verbose_name_plural': 'server roles'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('execute_server', 'Can execute command')]},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'permissions': [], 'verbose_name': 'token', 'verbose_name_plural': 'tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('kick_user', 'Can kick user'), ('view_settings', 'Can view settings'), ('view_capabilities', 'Can check capabilities')]},
        ),
    ]
