# Generated by Django 2.1.1 on 2019-01-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20181231_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='max_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
