# Generated by Django 2.1.1 on 2019-01-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20190107_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='max_players',
            new_name='max_clients',
        ),
    ]
