# Generated by Django 2.0.6 on 2018-07-13 00:03

from django.db import migrations, models
from django.template.defaultfilters import slugify


def forwards(apps, schema_editor):
    Country = apps.get_model('core', 'Country')
    for row in Country.objects.all():
        row.code = row.code.lower()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20190107_2232'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
