# Generated by Django 2.0.3 on 2018-03-12 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0046_auto_20180312_2134'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ('log', '0001_initial'),
  ]

  operations = [
    migrations.RenameModel(
      old_name='UserUsetime',
      new_name='UserOnlineTime',
    ),
  ]
