# Generated by Django 2.0.3 on 2018-03-16 22:04

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('log', '0004_auto_20180316_2203'),
  ]

  operations = [
    migrations.AlterModelOptions(
      name='userip',
      options={},
    ),
    migrations.AlterModelOptions(
      name='usernamespace',
      options={},
    ),
    migrations.AlterModelOptions(
      name='useronlinetime',
      options={},
    ),
  ]
