# Generated by Django 2.0.3 on 2018-03-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20180316_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userip',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='usernamespace',
            options={'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='useronlinetime',
            options={'permissions': []},
        ),
    ]
