# Generated by Django 2.0.3 on 2018-03-24 23:32

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('log', '0008_auto_20180320_2128'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='serveraction',
      name='user',
    ),
    migrations.DeleteModel(
      name='ServerAction',
    ),
  ]
