# Generated by Django 2.1.1 on 2019-01-07 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20181231_0040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0010_auto_20181231_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDataPoint',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_name', models.CharField(max_length=255)),
                ('time_left', models.FloatField()),
                ('time_up', models.FloatField()),
                ('is_online', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='UserOnlineTime',
            new_name='UserConnection',
        ),
    ]
