# Generated by Django 2.1.1 on 2019-01-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20190107_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverdatapoint',
            old_name='map_name',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='serverdatapoint',
            old_name='time_up',
            new_name='uptime',
        ),
    ]
