# Generated by Django 2.1.1 on 2019-01-07 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20190107_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerScore',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serverdatapoint',
            name='score',
            field=models.ManyToManyField(to='log.ServerScore'),
        ),
    ]
