# Generated by Django 2.1.1 on 2019-01-07 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20190107_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatapoint',
            name='time_left',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='serverdatapoint',
            name='uptime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
